// Copyright (c) 2026 The Blackcoin developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://opensource.org/license/mit/.
//
// ============================================================================
// Fixed-point staking-weight determinism tests
// ============================================================================
// Canonical data: src/test/data/staking_mr_table.h
// (generated by contrib/staking/gen_mr_table.py).
//
// These tests define the deterministic fixed-point curve and composition order
// used by the three-tier staking-weight calculation.
//
// NON-BREAKING BY DESIGN:
//   * The "canonical" suite below needs only the generated header and is always
//     compiled — it green-lights that the committed consensus table is intact.
//   * The "fixedpoint" suite calls production API only when
//     BLACKCOIN_STAKING_WEIGHTS is defined.
//
// Coverage:
//   * curve fidelity against the generated table
//   * fixed-point composition order
//   * overflow-safe kernel comparison
//   * fails-safe weight reduction under sub-1.0 multipliers
//   * no floating point in the kernel-weight path
// ----------------------------------------------------------------------------

#define BLACKCOIN_STAKING_WEIGHTS 1

#include <addresstype.h>
#include <coins.h>
#include <consensus/demurrage.h>
#include <consensus/params.h>
#include <test/data/staking_mr_table.h>

#include <arith_uint256.h>
#include <consensus/amount.h>
#include <pos.h>

#include <boost/test/unit_test.hpp>

#include <algorithm>
#include <cstdint>
#include <limits>
#include <vector>

using namespace blackcoin_staking_canonical;

// ----------------------------------------------------------------------------
// Always-on: the committed canonical table is internally consistent.
// (C++-side mirror of `gen_mr_table.py --check`; protects the consensus data
//  even before the kernel change lands.)
// ----------------------------------------------------------------------------
BOOST_AUTO_TEST_SUITE(staking_weight_fixedpoint_tests)

BOOST_AUTO_TEST_CASE(canonical_table_bounds_and_monotonic)
{
    BOOST_CHECK_EQUAL(kStakingMrPpm10k.size(), static_cast<size_t>(kNvMaxBlocks + 1));
    BOOST_CHECK_EQUAL(kStakingMrPpm10k.front(), kLiquidPpm10k); // r=0 -> 0.25x
    BOOST_CHECK_EQUAL(kStakingMrPpm10k.back(), kFullPpm10k);    // r=1 -> 1.00x
    BOOST_CHECK_EQUAL(kLiquidPpm10k, 2500);
    BOOST_CHECK_EQUAL(kFullPpm10k, 10000);
    BOOST_CHECK_EQUAL(kOperatorPpm10k, 10000); // Operator tier is FLAT 1.00x
    for (size_t i = 1; i < kStakingMrPpm10k.size(); ++i) {
        BOOST_CHECK_MESSAGE(kStakingMrPpm10k[i] >= kStakingMrPpm10k[i - 1],
                            "m(r) must be monotonic non-decreasing at index " << i);
        BOOST_CHECK(kStakingMrPpm10k[i] >= kLiquidPpm10k && kStakingMrPpm10k[i] <= kFullPpm10k);
    }
}

BOOST_AUTO_TEST_CASE(canonical_tier_checkpoints)
{
    // Tier points must match the frozen generator output exactly.
    BOOST_CHECK_EQUAL(kStakingMrPpm10k[0], kTierLiquid0d);     // 2500
    BOOST_CHECK_EQUAL(kStakingMrPpm10k[1350], kTierVault1d);   // 5335
    BOOST_CHECK_EQUAL(kStakingMrPpm10k[2700], kTierVault2d);   // 6509
    BOOST_CHECK_EQUAL(kStakingMrPpm10k[4725], kTierVault3p5d); // 7803
    BOOST_CHECK_EQUAL(kStakingMrPpm10k[6750], kTierVault5d);   // 8839
    BOOST_CHECK_EQUAL(kStakingMrPpm10k[9450], kTierVault7d);   // 10000
}

// ----------------------------------------------------------------------------
// Exercises the production tiered staking kernel-weight path. The production
// helpers are intentionally centralized so the miner and validator use the same
// fixed-point calculation:
//
//   // pos.cpp / a new staking_weight.{h,cpp}
//   uint16_t StakeWeightMultiplierPpm10k(int remaining_unbonding_blocks);
//   arith_uint256 EffectiveStakeWeight(CAmount nValueIn,
//                                       uint16_t m_ppm10k, uint16_t pool_ppm10k);
//   // 512-bit-safe kernel comparison:
//   bool KernelProductLE(const arith_uint256& bnTarget,
//                        const arith_uint256& bnWeight,
//                        const uint256& hashProofOfStake);
// ----------------------------------------------------------------------------
#if defined(BLACKCOIN_STAKING_WEIGHTS)

namespace {
CScript ScriptForWitnessProgram(unsigned int witness_version, const std::vector<unsigned char>& program)
{
    return GetScriptForDestination(WitnessUnknown{witness_version, program});
}

std::vector<unsigned char> TestPubkey(unsigned char tag)
{
    return std::vector<unsigned char>(1312, tag);
}
} // namespace

// Production multiplier reproduces the committed table exactly.
BOOST_AUTO_TEST_CASE(t1_curve_fidelity_runtime)
{
    for (int rem = 0; rem <= kNvMaxBlocks; ++rem) {
        BOOST_CHECK_EQUAL(StakeWeightMultiplierPpm10k(rem), kStakingMrPpm10k[rem]);
    }
    // Clamp: beyond Vault max stays at ceiling (Operator handled separately, flat).
    BOOST_CHECK_EQUAL(StakeWeightMultiplierPpm10k(kNvMaxBlocks + 100000), kFullPpm10k);
    BOOST_CHECK_EQUAL(StakeWeightMultiplierPpm10k(-5), kLiquidPpm10k);
}

// Composition order: weight = value * m/10000 * pool/10000 (multiply-then-
// divide per factor, on the weight only; never fold *10000 into bnTarget).
BOOST_AUTO_TEST_CASE(t2_composition_order)
{
    const CAmount v = 12345 * COIN;
    const arith_uint256 got = EffectiveStakeWeight(v, kTierVault3p5d, kPoolStakerPpm10k);
    arith_uint256 want = arith_uint256(static_cast<uint64_t>(v));
    want *= arith_uint256(kTierVault3p5d); want /= arith_uint256(10000);
    want *= arith_uint256(kPoolStakerPpm10k); want /= arith_uint256(10000);
    BOOST_CHECK(got == want);
    // Each intermediate must stay <= ~2^75 (value<=2^61 * ppm<=2^14). The
    // production code MUST NOT defer the divide past the bnTarget multiply.
}

// Overflow edge: bnTarget=posLimitV2, weight=MAX_MONEY at full multiplier.
// The kernel comparison must be evaluated without truncating mod 2^256.
BOOST_AUTO_TEST_CASE(t3_overflow_edge_no_truncation)
{
    const arith_uint256 bnTarget = UintToArith256(uint256S(
        // posLimitV2 ~ 2^208 (mainnet). Hex of kPosLimitV2Dec:
        "000000000000ffffffffffffffffffffffffffffffffffffffffffffffffffff"));
    const CAmount v = MAX_MONEY; // 2e18 sat
    const arith_uint256 bnWeight = EffectiveStakeWeight(v, kFullPpm10k, kPoolOwnerPpm10k);
    BOOST_CHECK(bnWeight == arith_uint256(static_cast<uint64_t>(MAX_MONEY))); // full mult == MAX_MONEY

    const arith_uint256 truncated = bnTarget * bnWeight;
    const uint256 max_hash = uint256S("ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff");
    BOOST_CHECK(UintToArith256(max_hash) > truncated);
    BOOST_CHECK(KernelProductLE(bnTarget, bnWeight, max_hash));

    const arith_uint256 small_target{2};
    const arith_uint256 small_weight{3};
    BOOST_CHECK(KernelProductLE(small_target, small_weight, ArithToUint256(arith_uint256{6})));
    BOOST_CHECK(!KernelProductLE(small_target, small_weight, ArithToUint256(arith_uint256{7})));
}

// Fails-safe direction: any sub-1.0 multiplier can only reduce weight.
BOOST_AUTO_TEST_CASE(t4_fails_safe_direction)
{
    const CAmount v = 1000 * COIN;
    const arith_uint256 full = EffectiveStakeWeight(v, kFullPpm10k, kPoolOwnerPpm10k);
    for (uint16_t m : {kLiquidPpm10k, kTierVault1d, kTierVault5d, kFullPpm10k}) {
        for (uint16_t p : {kPoolStakerPpm10k, kPoolOwnerPpm10k}) {
            const arith_uint256 got = EffectiveStakeWeight(v, m, p);
            BOOST_CHECK_MESSAGE(got <= full,
                "penalty must never increase weight (m=" << m << ", pool=" << p << ")");
        }
    }
}

BOOST_AUTO_TEST_CASE(t5_weight_context_gate_off_is_full_owner_weight)
{
    const std::vector<unsigned char> bonded_program = QuantumTieredMigrationProgramForPubkey(
        TestPubkey(0x01), QUANTUM_TIERED_STATE_BONDED, kNvMaxBlocks, 0);
    const CScript bonded_script = ScriptForWitnessProgram(QUANTUM_MIGRATION_WITNESS_VERSION, bonded_program);

    const StakeWeightContext context = GetStakeWeightContext(
        bonded_script,
        /*stake_input=*/nullptr,
        /*candidate_height=*/100,
        /*stake_tiers_active=*/false);

    BOOST_CHECK(!context.stake_tiers_active);
    BOOST_CHECK_EQUAL(context.multiplier_ppm10k, kFullPpm10k);
    BOOST_CHECK_EQUAL(context.pool_ppm10k, kPoolOwnerPpm10k);
    BOOST_CHECK_EQUAL(context.effective_unbonding_blocks, 0);
}

BOOST_AUTO_TEST_CASE(t6_weight_context_gate_on_liquid_defaults)
{
    const CScript liquid_script = ScriptForWitnessProgram(
        QUANTUM_MIGRATION_WITNESS_VERSION,
        QuantumMigrationProgramForPubkey(TestPubkey(0x02)));
    const StakeWeightContext liquid_context = GetStakeWeightContext(
        liquid_script,
        /*stake_input=*/nullptr,
        /*candidate_height=*/100,
        /*stake_tiers_active=*/true);
    BOOST_CHECK(liquid_context.stake_tiers_active);
    BOOST_CHECK_EQUAL(liquid_context.multiplier_ppm10k, kLiquidPpm10k);
    BOOST_CHECK_EQUAL(liquid_context.pool_ppm10k, kPoolOwnerPpm10k);
    BOOST_CHECK_EQUAL(liquid_context.effective_unbonding_blocks, 0);

    const std::vector<unsigned char> cold_program = QuantumColdStakeProgramForPubkeys(TestPubkey(0x03), TestPubkey(0x04));
    const CScript cold_script = ScriptForWitnessProgram(QUANTUM_COLDSTAKE_WITNESS_VERSION, cold_program);
    const StakeWeightContext cold_context = GetStakeWeightContext(
        cold_script,
        /*stake_input=*/nullptr,
        /*candidate_height=*/100,
        /*stake_tiers_active=*/true);
    BOOST_CHECK(cold_context.stake_tiers_active);
    BOOST_CHECK_EQUAL(cold_context.multiplier_ppm10k, kLiquidPpm10k);
    BOOST_CHECK_EQUAL(cold_context.pool_ppm10k, kPoolStakerPpm10k);
    BOOST_CHECK_EQUAL(cold_context.effective_unbonding_blocks, 0);
}

BOOST_AUTO_TEST_CASE(t7_weight_context_tiered_remaining_height_curve)
{
    const std::vector<unsigned char> bonded_program = QuantumTieredMigrationProgramForPubkey(
        TestPubkey(0x05), QUANTUM_TIERED_STATE_BONDED, 6750, 0);
    const StakeWeightContext bonded_context = GetStakeWeightContext(
        ScriptForWitnessProgram(QUANTUM_MIGRATION_WITNESS_VERSION, bonded_program),
        /*stake_input=*/nullptr,
        /*candidate_height=*/100,
        /*stake_tiers_active=*/true);
    BOOST_CHECK(bonded_context.stake_tiers_active);
    BOOST_CHECK_EQUAL(bonded_context.effective_unbonding_blocks, 6750);
    BOOST_CHECK_EQUAL(bonded_context.multiplier_ppm10k, kTierVault5d);
    BOOST_CHECK_EQUAL(bonded_context.pool_ppm10k, kPoolOwnerPpm10k);

    const std::vector<unsigned char> unbonding_program = QuantumTieredMigrationProgramForPubkey(
        TestPubkey(0x06), QUANTUM_TIERED_STATE_UNBONDING, kNvMaxBlocks, 3350);
    const CScript unbonding_script = ScriptForWitnessProgram(QUANTUM_MIGRATION_WITNESS_VERSION, unbonding_program);
    const StakeWeightContext pre_unlock_context = GetStakeWeightContext(
        unbonding_script,
        /*stake_input=*/nullptr,
        /*candidate_height=*/2000,
        /*stake_tiers_active=*/true);
    BOOST_CHECK_EQUAL(pre_unlock_context.effective_unbonding_blocks, 1350);
    BOOST_CHECK_EQUAL(pre_unlock_context.multiplier_ppm10k, kTierVault1d);

    const StakeWeightContext post_unlock_context = GetStakeWeightContext(
        unbonding_script,
        /*stake_input=*/nullptr,
        /*candidate_height=*/3350,
        /*stake_tiers_active=*/true);
    BOOST_CHECK_EQUAL(post_unlock_context.effective_unbonding_blocks, 0);
    BOOST_CHECK_EQUAL(post_unlock_context.multiplier_ppm10k, kLiquidPpm10k);
}

BOOST_AUTO_TEST_CASE(t8_weight_context_qcs_tiered_pool_penalty)
{
    const std::vector<unsigned char> cold_program = QuantumTieredColdStakeProgramForPubkeys(
        TestPubkey(0x07), TestPubkey(0x08), QUANTUM_TIERED_STATE_BONDED, 4725, 0);
    const CScript cold_script = ScriptForWitnessProgram(QUANTUM_COLDSTAKE_WITNESS_VERSION, cold_program);
    const StakeWeightContext context = GetStakeWeightContext(
        cold_script,
        /*stake_input=*/nullptr,
        /*candidate_height=*/100,
        /*stake_tiers_active=*/true);

    BOOST_CHECK(context.stake_tiers_active);
    BOOST_CHECK_EQUAL(context.effective_unbonding_blocks, 4725);
    BOOST_CHECK_EQUAL(context.multiplier_ppm10k, kTierVault3p5d);
    BOOST_CHECK_EQUAL(context.pool_ppm10k, kPoolStakerPpm10k);
}

BOOST_AUTO_TEST_CASE(t9_demurrage_kernel_value_gate_off_is_nominal)
{
    Consensus::Params params;
    params.nDemurrageActivationHeight = std::numeric_limits<int>::max();
    params.nQuantumMigrationDeadlineTime = 100;

    const CScript script = ScriptForWitnessProgram(
        QUANTUM_MIGRATION_WITNESS_VERSION,
        QuantumMigrationProgramForPubkey(TestPubkey(0x09)));
    const Coin coin{CTxOut{10 * COIN, script}, /*nHeight=*/1, /*fCoinBase=*/false, /*fCoinStake=*/false, /*nTime=*/0};

    CCoinsView dummy;
    CCoinsViewCache view{&dummy};
    const int spend_height = coin.nHeight + Consensus::DEMURRAGE_ZERO_BLOCKS + 1;
    const int64_t spend_time = params.nQuantumMigrationDeadlineTime + 1;

    BOOST_CHECK(!params.IsDemurrageActive(spend_height, spend_time));
    BOOST_CHECK_EQUAL(GetKernelStakeValue(coin, view, params, spend_height, spend_time), coin.out.nValue);
    BOOST_CHECK(EffectiveStakeWeight(GetKernelStakeValue(coin, view, params, spend_height, spend_time), kFullPpm10k, kPoolOwnerPpm10k) ==
                EffectiveStakeWeight(coin.out.nValue, kFullPpm10k, kPoolOwnerPpm10k));
}

BOOST_AUTO_TEST_CASE(t10_demurrage_kernel_weight_scales_with_effective_value)
{
    Consensus::Params params;
    params.nDemurrageActivationHeight = 1;
    params.nQuantumMigrationDeadlineTime = 100;

    const CScript script = ScriptForWitnessProgram(
        QUANTUM_MIGRATION_WITNESS_VERSION,
        QuantumMigrationProgramForPubkey(TestPubkey(0x0a)));
    const Coin coin{CTxOut{10 * COIN, script}, /*nHeight=*/1, /*fCoinBase=*/false, /*fCoinStake=*/false, /*nTime=*/0};

    CCoinsView dummy;
    CCoinsViewCache view{&dummy};
    const int spend_height = coin.nHeight + params.DemurrageGraceBlocks() + (params.DemurrageDecayWindowBlocks() / 2);
    const int64_t spend_time = params.nQuantumMigrationDeadlineTime + 1;

    BOOST_REQUIRE(params.IsDemurrageActive(spend_height, spend_time));
    const Consensus::DemurrageEvaluation eval = Consensus::EvaluateDemurrage(coin, params, spend_height, spend_time);
    BOOST_REQUIRE_GT(eval.remaining_ppm, 0);
    BOOST_REQUIRE_LT(eval.remaining_ppm, Consensus::DEMURRAGE_PPM);
    BOOST_REQUIRE_LT(eval.effective_value, coin.out.nValue);

    const CAmount kernel_value = GetKernelStakeValue(coin, view, params, spend_height, spend_time);
    BOOST_CHECK_EQUAL(kernel_value, eval.effective_value);
    BOOST_CHECK(EffectiveStakeWeight(kernel_value, kFullPpm10k, kPoolOwnerPpm10k) ==
                EffectiveStakeWeight(eval.effective_value, kFullPpm10k, kPoolOwnerPpm10k));
}

BOOST_AUTO_TEST_CASE(t11_demurrage_locked_kernel_weight_is_zero)
{
    Consensus::Params params;
    params.nDemurrageActivationHeight = 1;
    params.nQuantumMigrationDeadlineTime = 100;

    const CScript script = ScriptForWitnessProgram(
        QUANTUM_MIGRATION_WITNESS_VERSION,
        QuantumMigrationProgramForPubkey(TestPubkey(0x0b)));
    const Coin coin{CTxOut{10 * COIN, script}, /*nHeight=*/1, /*fCoinBase=*/false, /*fCoinStake=*/false, /*nTime=*/0};

    CCoinsView dummy;
    CCoinsViewCache view{&dummy};
    const int spend_height = coin.nHeight + params.DemurrageZeroBlocks() + 1;
    const int64_t spend_time = params.nQuantumMigrationDeadlineTime + 1;

    const Consensus::DemurrageEvaluation eval = Consensus::EvaluateDemurrage(coin, params, spend_height, spend_time);
    BOOST_REQUIRE(eval.locked);
    BOOST_CHECK_EQUAL(GetKernelStakeValue(coin, view, params, spend_height, spend_time), 0);
    BOOST_CHECK(EffectiveStakeWeight(GetKernelStakeValue(coin, view, params, spend_height, spend_time), kFullPpm10k, kPoolOwnerPpm10k) == arith_uint256(0));
}

BOOST_AUTO_TEST_CASE(t12_demurrage_coldstake_kernel_value_stays_nominal)
{
    Consensus::Params params;
    params.nDemurrageActivationHeight = 1;
    params.nQuantumMigrationDeadlineTime = 100;

    const std::vector<unsigned char> cold_program = QuantumColdStakeProgramForPubkeys(TestPubkey(0x0c), TestPubkey(0x0d));
    const CScript script = ScriptForWitnessProgram(QUANTUM_COLDSTAKE_WITNESS_VERSION, cold_program);
    const Coin coin{CTxOut{10 * COIN, script}, /*nHeight=*/1, /*fCoinBase=*/false, /*fCoinStake=*/false, /*nTime=*/0};

    CCoinsView dummy;
    CCoinsViewCache view{&dummy};
    const int spend_height = coin.nHeight + params.DemurrageZeroBlocks() + 1;
    const int64_t spend_time = params.nQuantumMigrationDeadlineTime + 1;

    BOOST_REQUIRE(params.IsDemurrageActive(spend_height, spend_time));
    const Consensus::DemurrageEvaluation eval = Consensus::EvaluateDemurrage(coin, params, spend_height, spend_time);
    BOOST_REQUIRE(eval.exempt);
    BOOST_CHECK_EQUAL(eval.exemption, "coldstake");
    BOOST_CHECK_EQUAL(GetKernelStakeValue(coin, view, params, spend_height, spend_time), coin.out.nValue);
}

#endif // BLACKCOIN_STAKING_WEIGHTS

BOOST_AUTO_TEST_SUITE_END()

// No-float gate: enforced by the build-system lint step:
//   ! grep -nE '\b(float|double)\b' src/pos.cpp src/staking_weight.cpp
// The kernel weight path must contain no floating point.
