// Copyright (c) 2010 Satoshi Nakamoto
// Copyright (c) 2009-2022 Blackcoin Core Developers
// Copyright (c) 2009-2022 Blackcoin More Developers
// Copyright (c) 2009-2022 Blackcoin Developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#include <key_io.h>
#include <addresstype.h>
#include <crypto/mldsa.h>
#include <crypto/sha256.h>
#include <outputtype.h>
#include <pubkey.h>
#include <rpc/protocol.h>
#include <rpc/request.h>
#include <rpc/server.h>
#include <rpc/util.h>
#include <script/descriptor.h>
#include <script/script.h>
#include <script/signingprovider.h>
#include <script/solver.h>
#include <tinyformat.h>
#include <univalue.h>
#include <uint256.h>
#include <util/check.h>
#include <util/strencodings.h>

#include <cstdint>
#include <memory>
#include <optional>
#include <string>
#include <tuple>
#include <vector>

static RPCHelpMan validateaddress()
{
    return RPCHelpMan{
        "validateaddress",
        "\nReturn information about the given Blackcoin address.\n",
        {
            {"address", RPCArg::Type::STR, RPCArg::Optional::NO, "The Blackcoin address to validate"},
        },
        RPCResult{
            RPCResult::Type::OBJ, "", "",
            {
                {RPCResult::Type::BOOL, "isvalid", "If the address is valid or not"},
                {RPCResult::Type::STR, "address", /*optional=*/true, "The Blackcoin address validated"},
                {RPCResult::Type::STR_HEX, "scriptPubKey", /*optional=*/true, "The hex-encoded scriptPubKey generated by the address"},
                {RPCResult::Type::BOOL, "isscript", /*optional=*/true, "If the key is a script"},
                {RPCResult::Type::BOOL, "iswitness", /*optional=*/true, "If the address is a witness address"},
                {RPCResult::Type::NUM, "witness_version", /*optional=*/true, "The version number of the witness program"},
                {RPCResult::Type::STR_HEX, "witness_program", /*optional=*/true, "The hex value of the witness program"},
                {RPCResult::Type::BOOL, "isquantummigration", /*optional=*/true, "Whether this is a Blackcoin post-quantum migration reservation address"},
                {RPCResult::Type::BOOL, "isquantumcoldstake", /*optional=*/true, "Whether this is a Blackcoin cold-staking address"},
                {RPCResult::Type::BOOL, "fundable_now", /*optional=*/true, "Whether ordinary wallet/RPC policy currently permits funding this address type"},
                {RPCResult::Type::BOOL, "spendable_now", /*optional=*/true, "Whether this node can currently sign/spend this address type"},
                {RPCResult::Type::BOOL, "quantum_spend_enforced", /*optional=*/true, "Whether quantum signature spend enforcement is active for this address type"},
                {RPCResult::Type::BOOL, "consensus_spend_guard_active", /*optional=*/true, "Whether reserved migration spends are rejected until final quantum rules exist"},
                {RPCResult::Type::STR, "migration_note", /*optional=*/true, "Quantum migration status note"},
                {RPCResult::Type::STR, "error", /*optional=*/true, "Error message, if any"},
                {RPCResult::Type::ARR, "error_locations", /*optional=*/true, "Indices of likely error locations in address, if known (e.g. Bech32 errors)",
                    {
                        {RPCResult::Type::NUM, "index", "index of a potential error"},
                    }},
            }
        },
        RPCExamples{
            HelpExampleCli("validateaddress", "\"" + EXAMPLE_ADDRESS[0] + "\"") +
            HelpExampleRpc("validateaddress", "\"" + EXAMPLE_ADDRESS[0] + "\"")
        },
        [&](const RPCHelpMan& self, const JSONRPCRequest& request) -> UniValue
        {
            std::string error_msg;
            std::vector<int> error_locations;
            CTxDestination dest = DecodeDestination(request.params[0].get_str(), error_msg, &error_locations);
            const bool isValid = IsValidDestination(dest);
            const bool isQuantumMigration = IsQuantumMigrationDestination(dest);
            CHECK_NONFATAL(isValid == error_msg.empty() || isQuantumMigration);

            UniValue ret(UniValue::VOBJ);
            ret.pushKV("isvalid", isValid);
            if (isValid || isQuantumMigration) {
                std::string currentAddress = EncodeDestination(dest);
                ret.pushKV("address", currentAddress);

                if (isValid) {
                    CScript scriptPubKey = GetScriptForDestination(dest);
                    ret.pushKV("scriptPubKey", HexStr(scriptPubKey));
                }

                UniValue detail = DescribeAddress(dest);
                ret.pushKVs(detail);
            } else {
                UniValue error_indices(UniValue::VARR);
                for (int i : error_locations) error_indices.push_back(i);
                ret.pushKV("error_locations", error_indices);
                ret.pushKV("error", error_msg);
            }

            return ret;
        },
    };
}

static RPCHelpMan createquantummigrationaddress()
{
    return RPCHelpMan{
        "createquantummigrationaddress",
        "\nEncodes a 32-byte post-quantum migration commitment as a Blackcoin witness-v16 address.\n"
        "For native ML-DSA keys, the commitment is SHA256(public_key). Funds sent before the migration\n"
        "window are locked until ML-DSA spend enforcement activates by schedule.\n",
        {
            {"commitment", RPCArg::Type::STR_HEX, RPCArg::Optional::NO, "32-byte hex commitment, normally SHA256(ML-DSA public key)"},
        },
        RPCResult{
            RPCResult::Type::OBJ, "", "", {
                {RPCResult::Type::STR, "address", "The encoded Blackcoin migration reservation identifier"},
                {RPCResult::Type::BOOL, "isvalid_destination", "Whether ordinary wallet/RPC address paths currently accept this as a payment destination"},
                {RPCResult::Type::NUM, "witness_version", "The witness version reserved for quantum migration"},
                {RPCResult::Type::STR_HEX, "witness_program", "The 32-byte migration commitment"},
                {RPCResult::Type::BOOL, "fundable_now", "Whether ordinary wallet/RPC policy currently permits funding this address type"},
                {RPCResult::Type::BOOL, "spendable_now", "Whether this node can currently sign/spend this address type"},
                {RPCResult::Type::BOOL, "consensus_spend_guard_active", "Whether this node still treats migration spends as permanently disabled"},
                {RPCResult::Type::STR, "warning", "Migration warning"},
            }},
        RPCExamples{
            HelpExampleCli("createquantummigrationaddress", "0000000000000000000000000000000000000000000000000000000000000000")
            + HelpExampleRpc("createquantummigrationaddress", "\"0000000000000000000000000000000000000000000000000000000000000000\"")
        },
        [&](const RPCHelpMan& self, const JSONRPCRequest& request) -> UniValue
{
    const std::string commitment_hex = request.params[0].get_str();
    if (!IsHex(commitment_hex)) {
        throw JSONRPCError(RPC_INVALID_PARAMETER, "commitment must be hex");
    }
    const std::vector<unsigned char> commitment = ParseHex(commitment_hex);
    if (commitment.size() != QUANTUM_MIGRATION_PROGRAM_SIZE) {
        throw JSONRPCError(RPC_INVALID_PARAMETER, strprintf("commitment must be exactly %u bytes", QUANTUM_MIGRATION_PROGRAM_SIZE));
    }

    const CTxDestination dest = WitnessUnknown{QUANTUM_MIGRATION_WITNESS_VERSION, commitment};

    UniValue ret(UniValue::VOBJ);
    ret.pushKV("address", EncodeDestination(dest));
    ret.pushKV("isvalid_destination", IsValidDestination(dest));
    ret.pushKV("witness_version", QUANTUM_MIGRATION_WITNESS_VERSION);
    ret.pushKV("witness_program", HexStr(commitment));
    ret.pushKV("fundable_now", true);
    ret.pushKV("spendable_now", false);
    ret.pushKV("consensus_spend_guard_active", false);
    ret.pushKV("warning", "Address is fundable. It is spendable only by the ML-DSA private key whose public key hashes to this witness program once quantum witness spending is active.");
    return ret;
},
    };
}

static RPCHelpMan createquantumkey()
{
    return RPCHelpMan{
        "createquantumkey",
        "\nGenerates an ML-DSA-44 keypair and its Blackcoin witness-v16 migration address.\n"
        "The returned private key is raw hex and is not stored in the wallet.\n",
        {},
        RPCResult{
            RPCResult::Type::OBJ, "", "", {
                {RPCResult::Type::STR, "address", "The Blackcoin migration address"},
                {RPCResult::Type::STR_HEX, "public_key", "The ML-DSA-44 public key"},
                {RPCResult::Type::STR_HEX, "private_key", "The ML-DSA-44 private key. Back it up immediately."},
                {RPCResult::Type::NUM, "witness_version", "The witness version used for quantum migration"},
                {RPCResult::Type::STR_HEX, "witness_program", "SHA256(public_key)"},
                {RPCResult::Type::BOOL, "stored_in_wallet", "Whether this key was inserted into the wallet database"},
                {RPCResult::Type::STR, "warning", "Key storage warning"},
            }},
        RPCExamples{
            HelpExampleCli("createquantumkey", "")
            + HelpExampleRpc("createquantumkey", "")
        },
        [&](const RPCHelpMan& self, const JSONRPCRequest& request) -> UniValue
{
    std::vector<uint8_t> pubkey;
    std::vector<uint8_t> privkey;
    if (!ML_DSA::KeyGen(pubkey, privkey)) {
        throw JSONRPCError(RPC_MISC_ERROR, "ML-DSA key generation failed");
    }

    std::vector<unsigned char> program(QUANTUM_MIGRATION_PROGRAM_SIZE);
    CSHA256().Write(pubkey.data(), pubkey.size()).Finalize(program.data());
    const CTxDestination dest = WitnessUnknown{QUANTUM_MIGRATION_WITNESS_VERSION, program};

    UniValue ret(UniValue::VOBJ);
    ret.pushKV("address", EncodeDestination(dest));
    ret.pushKV("public_key", HexStr(pubkey));
    ret.pushKV("private_key", HexStr(privkey));
    ret.pushKV("witness_version", QUANTUM_MIGRATION_WITNESS_VERSION);
    ret.pushKV("witness_program", HexStr(program));
    ret.pushKV("stored_in_wallet", false);
    ret.pushKV("warning", "This key is not stored in the wallet database. Loss of the private_key permanently loses funds sent to this address.");
    // Wipe the raw ML-DSA secret from the heap before the buffer is freed.
    memory_cleanse(privkey.data(), privkey.size());
    return ret;
},
    };
}


static RPCHelpMan createmultisig()
{
    return RPCHelpMan{"createmultisig",
        "\nCreates a multi-signature address with n signature of m keys required.\n"
        "It returns a json object with the address and redeemScript.\n",
        {
            {"nrequired", RPCArg::Type::NUM, RPCArg::Optional::NO, "The number of required signatures out of the n keys."},
            {"keys", RPCArg::Type::ARR, RPCArg::Optional::NO, "The hex-encoded public keys.",
                {
                    {"key", RPCArg::Type::STR_HEX, RPCArg::Optional::OMITTED, "The hex-encoded public key"},
                }},
            {"address_type", RPCArg::Type::STR, RPCArg::Default{"legacy"}, "The address type to use. Options are \"legacy\", \"p2sh-segwit\", and \"bech32\"."},
        },
        RPCResult{
            RPCResult::Type::OBJ, "", "",
            {
                {RPCResult::Type::STR, "address", "The value of the new multisig address."},
                {RPCResult::Type::STR_HEX, "redeemScript", "The string value of the hex-encoded redemption script."},
                {RPCResult::Type::STR, "descriptor", "The descriptor for this multisig"},
                {RPCResult::Type::ARR, "warnings", /*optional=*/true, "Any warnings resulting from the creation of this multisig",
                {
                    {RPCResult::Type::STR, "", ""},
                }},
            }
        },
        RPCExamples{
            "\nCreate a multisig address from 2 public keys\n"
            + HelpExampleCli("createmultisig", "2 \"[\\\"03789ed0bb717d88f7d321a368d905e7430207ebbd82bd342cf11ae157a7ace5fd\\\",\\\"03dbc6764b8884a92e871274b87583e6d5c2a58819473e17e107ef3f6aa5a61626\\\"]\"") +
            "\nAs a JSON-RPC call\n"
            + HelpExampleRpc("createmultisig", "2, [\"03789ed0bb717d88f7d321a368d905e7430207ebbd82bd342cf11ae157a7ace5fd\",\"03dbc6764b8884a92e871274b87583e6d5c2a58819473e17e107ef3f6aa5a61626\"]")
                },
        [&](const RPCHelpMan& self, const JSONRPCRequest& request) -> UniValue
        {
            int required = request.params[0].getInt<int>();

            // Get the public keys
            const UniValue& keys = request.params[1].get_array();
            std::vector<CPubKey> pubkeys;
            for (unsigned int i = 0; i < keys.size(); ++i) {
                if (IsHex(keys[i].get_str()) && (keys[i].get_str().length() == 66 || keys[i].get_str().length() == 130)) {
                    pubkeys.push_back(HexToPubKey(keys[i].get_str()));
                } else {
                    throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, strprintf("Invalid public key: %s\n.", keys[i].get_str()));
                }
            }

            // Get the output type
            OutputType output_type = OutputType::LEGACY;
            if (!request.params[2].isNull()) {
                std::optional<OutputType> parsed = ParseOutputType(request.params[2].get_str());
                if (!parsed) {
                    throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, strprintf("Unknown address type '%s'", request.params[2].get_str()));
                } else if (parsed.value() == OutputType::BECH32M) {
                    throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "createmultisig cannot create bech32m multisig addresses");
                }
                output_type = parsed.value();
            }

            // Construct using pay-to-script-hash:
            FillableSigningProvider keystore;
            CScript inner;
            const CTxDestination dest = AddAndGetMultisigDestination(required, pubkeys, output_type, keystore, inner);

            // Make the descriptor
            std::unique_ptr<Descriptor> descriptor = InferDescriptor(GetScriptForDestination(dest), keystore);

            UniValue result(UniValue::VOBJ);
            result.pushKV("address", EncodeDestination(dest));
            result.pushKV("redeemScript", HexStr(inner));
            result.pushKV("descriptor", descriptor->ToString());

            UniValue warnings(UniValue::VARR);
            if (descriptor->GetOutputType() != output_type) {
                // Only warns if the user has explicitly chosen an address type we cannot generate
                warnings.push_back("Unable to make chosen address type, please ensure no uncompressed public keys are present.");
            }
            PushWarnings(warnings, result);

            return result;
        },
    };
}

static RPCHelpMan getdescriptorinfo()
{
    const std::string EXAMPLE_DESCRIPTOR = "wpkh([d34db33f/84h/0h/0h]0279be667ef9dcbbac55a06295Ce870b07029Bfcdb2dce28d959f2815b16f81798)";

    return RPCHelpMan{"getdescriptorinfo",
        {"\nAnalyses a descriptor.\n"},
        {
            {"descriptor", RPCArg::Type::STR, RPCArg::Optional::NO, "The descriptor."},
        },
        RPCResult{
            RPCResult::Type::OBJ, "", "",
            {
                {RPCResult::Type::STR, "descriptor", "The descriptor in canonical form, without private keys"},
                {RPCResult::Type::STR, "checksum", "The checksum for the input descriptor"},
                {RPCResult::Type::BOOL, "isrange", "Whether the descriptor is ranged"},
                {RPCResult::Type::BOOL, "issolvable", "Whether the descriptor is solvable"},
                {RPCResult::Type::BOOL, "hasprivatekeys", "Whether the input descriptor contained at least one private key"},
            }
        },
        RPCExamples{
            "Analyse a descriptor\n" +
            HelpExampleCli("getdescriptorinfo", "\"" + EXAMPLE_DESCRIPTOR + "\"") +
            HelpExampleRpc("getdescriptorinfo", "\"" + EXAMPLE_DESCRIPTOR + "\"")
        },
        [&](const RPCHelpMan& self, const JSONRPCRequest& request) -> UniValue
        {
            FlatSigningProvider provider;
            std::string error;
            auto desc = Parse(request.params[0].get_str(), provider, error);
            if (!desc) {
                throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, error);
            }

            UniValue result(UniValue::VOBJ);
            result.pushKV("descriptor", desc->ToString());
            result.pushKV("checksum", GetDescriptorChecksum(request.params[0].get_str()));
            result.pushKV("isrange", desc->IsRange());
            result.pushKV("issolvable", desc->IsSolvable());
            result.pushKV("hasprivatekeys", provider.keys.size() > 0);
            return result;
        },
    };
}

static RPCHelpMan deriveaddresses()
{
    const std::string EXAMPLE_DESCRIPTOR = "wpkh([d34db33f/84h/0h/0h]xpub6DJ2dNUysrn5Vt36jH2KLBT2i1auw1tTSSomg8PhqNiUtx8QX2SvC9nrHu81fT41fvDUnhMjEzQgXnQjKEu3oaqMSzhSrHMxyyoEAmUHQbY/0/*)#cjjspncu";

    return RPCHelpMan{"deriveaddresses",
        {"\nDerives one or more addresses corresponding to an output descriptor.\n"
         "Examples of output descriptors are:\n"
         "    pkh(<pubkey>)                                     P2PKH outputs for the given pubkey\n"
         "    wpkh(<pubkey>)                                    Native segwit P2PKH outputs for the given pubkey\n"
         "    sh(multi(<n>,<pubkey>,<pubkey>,...))              P2SH-multisig outputs for the given threshold and pubkeys\n"
         "    raw(<hex script>)                                 Outputs whose scriptPubKey equals the specified hex scripts\n"
         "    tr(<pubkey>,multi_a(<n>,<pubkey>,<pubkey>,...))   P2TR-multisig outputs for the given threshold and pubkeys\n"
         "\nIn the above, <pubkey> either refers to a fixed public key in hexadecimal notation, or to an xpub/xprv optionally followed by one\n"
         "or more path elements separated by \"/\", where \"h\" represents a hardened child key.\n"
         "For more information on output descriptors, see the documentation in the doc/descriptors.md file.\n"},
        {
            {"descriptor", RPCArg::Type::STR, RPCArg::Optional::NO, "The descriptor."},
            {"range", RPCArg::Type::RANGE, RPCArg::Optional::OMITTED, "If a ranged descriptor is used, this specifies the end or the range (in [begin,end] notation) to derive."},
        },
        RPCResult{
            RPCResult::Type::ARR, "", "",
            {
                {RPCResult::Type::STR, "address", "the derived addresses"},
            }
        },
        RPCExamples{
            "First three native segwit receive addresses\n" +
            HelpExampleCli("deriveaddresses", "\"" + EXAMPLE_DESCRIPTOR + "\" \"[0,2]\"") +
            HelpExampleRpc("deriveaddresses", "\"" + EXAMPLE_DESCRIPTOR + "\", \"[0,2]\"")
        },
        [&](const RPCHelpMan& self, const JSONRPCRequest& request) -> UniValue
        {
            const std::string desc_str = request.params[0].get_str();

            int64_t range_begin = 0;
            int64_t range_end = 0;

            if (request.params.size() >= 2 && !request.params[1].isNull()) {
                std::tie(range_begin, range_end) = ParseDescriptorRange(request.params[1]);
            }

            FlatSigningProvider key_provider;
            std::string error;
            auto desc = Parse(desc_str, key_provider, error, /* require_checksum = */ true);
            if (!desc) {
                throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, error);
            }

            if (!desc->IsRange() && request.params.size() > 1) {
                throw JSONRPCError(RPC_INVALID_PARAMETER, "Range should not be specified for an un-ranged descriptor");
            }

            if (desc->IsRange() && request.params.size() == 1) {
                throw JSONRPCError(RPC_INVALID_PARAMETER, "Range must be specified for a ranged descriptor");
            }

            UniValue addresses(UniValue::VARR);

            for (int64_t i = range_begin; i <= range_end; ++i) {
                FlatSigningProvider provider;
                std::vector<CScript> scripts;
                if (!desc->Expand(i, key_provider, scripts, provider)) {
                    throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "Cannot derive script without private keys");
                }

                for (const CScript& script : scripts) {
                    CTxDestination dest;
                    if (!ExtractDestination(script, dest)) {
                        // ExtractDestination no longer returns true for P2PK since it doesn't have a corresponding address
                        // However combo will output P2PK and should just ignore that script
                        if (scripts.size() > 1 && std::get_if<PubKeyDestination>(&dest)) {
                            continue;
                        }
                        throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "Descriptor does not have a corresponding address");
                    }

                    addresses.push_back(EncodeDestination(dest));
                }
            }

            // This should not be possible, but an assert seems overkill:
            if (addresses.empty()) {
                throw JSONRPCError(RPC_MISC_ERROR, "Unexpected empty result");
            }

            return addresses;
        },
    };
}

static RPCHelpMan createcoldstakingaddress()
{
    return RPCHelpMan{"createcoldstakingaddress",
        "\nBuild a quantum-only cold-staking delegation address from two ML-DSA public keys.\n"
        "The staking (hot) key may spend the coins only inside a coinstake transaction; the owner\n"
        "(cold) key may spend them unconditionally at any time. The returned address is a native\n"
        "Quantum Cold-Stake witness program, not an ECDSA/P2WSH script.\n"
        "\nTrust model: the witness program commits to SHA256(staking_pubkey) and SHA256(owner_pubkey).\n"
        "Consensus verifies ML-DSA directly at witness-program level. V4 additionally requires any\n"
        "coinstake spending these coins to return at least the principal to this same address. Cold-stake\n"
        "blocks earn a reduced base subsidy; regular full-node self-staking remains the favored reward path.\n"
        "The owner branch is for ordinary spends only; delegated coinstakes must use the staking branch.\n",
        {
            {"owner_pubkey", RPCArg::Type::STR_HEX, RPCArg::Optional::NO, "Owner (cold) ML-DSA-44 public key with unconditional spend control."},
            {"staking_pubkey", RPCArg::Type::STR_HEX, RPCArg::Optional::NO, "Staking (hot) ML-DSA-44 public key allowed to spend only inside coinstakes."},
        },
        RPCResult{RPCResult::Type::OBJ, "", "", {
            {RPCResult::Type::STR, "address", "The Quantum Cold-Stake deposit address."},
            {RPCResult::Type::NUM, "witness_version", "The reserved Quantum Cold-Stake witness version."},
            {RPCResult::Type::STR_HEX, "witness_program", "The 32-byte Quantum Cold-Stake commitment."},
            {RPCResult::Type::STR_HEX, "scriptPubKey", "The native witness scriptPubKey."},
            {RPCResult::Type::STR_HEX, "owner_pubkey_hash", "SHA256(owner_pubkey), needed in staker-branch witness templates."},
            {RPCResult::Type::STR_HEX, "staking_pubkey_hash", "SHA256(staking_pubkey), needed in owner-branch witness templates."},
            {RPCResult::Type::STR, "warning", "Trust-model note."},
        }},
        RPCExamples{
            HelpExampleCli("createcoldstakingaddress", "\"<owner_pubkey>\" \"<staking_pubkey>\"")
          + HelpExampleRpc("createcoldstakingaddress", "\"<owner_pubkey>\", \"<staking_pubkey>\"")
        },
    [&](const RPCHelpMan& self, const JSONRPCRequest& request) -> UniValue
{
    const std::vector<unsigned char> owner_key = ParseHexV(request.params[0], "owner_pubkey");
    if (owner_key.size() != ML_DSA::PUBLICKEY_BYTES) {
        throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, strprintf("owner_pubkey must be an ML-DSA public key (%u bytes)", ML_DSA::PUBLICKEY_BYTES));
    }
    const std::vector<unsigned char> staking_key = ParseHexV(request.params[1], "staking_pubkey");
    if (staking_key.size() != ML_DSA::PUBLICKEY_BYTES) {
        throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, strprintf("staking_pubkey must be an ML-DSA public key (%u bytes)", ML_DSA::PUBLICKEY_BYTES));
    }

    const std::vector<unsigned char> program = QuantumColdStakeProgramForPubkeys(staking_key, owner_key);
    const std::vector<unsigned char> owner_hash = QuantumMigrationProgramForPubkey(owner_key);
    const std::vector<unsigned char> staking_hash = QuantumMigrationProgramForPubkey(staking_key);
    const CTxDestination dest{WitnessUnknown{QUANTUM_COLDSTAKE_WITNESS_VERSION, program}};
    const CScript spk = GetScriptForDestination(dest);

    UniValue r(UniValue::VOBJ);
    r.pushKV("address", EncodeDestination(dest));
    r.pushKV("witness_version", QUANTUM_COLDSTAKE_WITNESS_VERSION);
    r.pushKV("witness_program", HexStr(program));
    r.pushKV("scriptPubKey", HexStr(spk));
    r.pushKV("owner_pubkey_hash", HexStr(owner_hash));
    r.pushKV("staking_pubkey_hash", HexStr(staking_hash));
    r.pushKV("warning", "Quantum-only cold staking. Owner branch witness selector is empty, supplies staking_pubkey_hash, and is valid only for ordinary spends. Staker branch selector is 01, supplies owner_pubkey_hash, and is required for delegated coinstakes. Automated delegated staking requires wallet metadata/import support.");
    return r;
},
    };
}

void RegisterOutputScriptRPCCommands(CRPCTable& t)
{
    static const CRPCCommand commands[]{
        {"util", &validateaddress},
        {"util", &createquantummigrationaddress},
        {"util", &createcoldstakingaddress},
        {"util", &createquantumkey},
        {"util", &createmultisig},
        {"util", &deriveaddresses},
        {"util", &getdescriptorinfo},
    };
    for (const auto& c : commands) {
        t.appendCommand(c.name, &c);
    }
}
